### ISSUE TITLE
Field guide: Better messaging when too many species are included

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/fieldguide#30]
Raised in https://support.ehelp.edu.au/a/tickets/187816

Currently, when attempting to generate a field guide with more than approx 100 species:
* The download page will shortly indicate "Your download is ready"
* The download button will link to a PDF file, eg https://api.ala.org.au/fieldguide/download/24102023-fieldguide1698119680318.pdf
* Clicking that link will show only the text `{"message": "Internal server error"}`
* That same link is also emailed to the user as per normal download behaviour

Example query (~700 species) from Explore your area: https://biocache.ala.org.au/occurrences/search?file=records-2023-10-24&reasonTypeId=10&dwcHeaders=true&fileType=csv&qa=none&sourceTypeId=0&q=*%3A*&qualityProfile=ALA&fq=geospatial_kosher%3Atrue&qc=-_nest_parent_%3A*&lat=-35.3095&lon=149.159&radius=1.0&&pageSize=0&&facet=true&#tab_recordImages

Ideal outcome:
* If a field guide cannot be generated due to including too many species, the download page should show an error instead of "Your download is ready"
* No link should be sent to the user via email either
* Specifically, the error message should say there were too many species included, and/or the field guide system should prevent a user attempting to create a file that won't work.
* Field guide is a very visible system, and users often seem to follow a path from Explore your area -> creating a field guide. We should make this as user-friendly as possible, potentially including increasing the number of species that can be added to a field guide.

**Comment by adam-collins** [comment]
- I think the ideal outcome is that it does not fail. Note that we do not keep these file indefinitely. e.g. today there are only fieldguides as old as 2023-10-26 and the example given is older.
- You cannot download files that large through the gateway so even if it was generated correctly that URL is not supported.
- That URL has since been replaced with a working one.
- Work to support the gateway is ongoing and will likely keep the files around much longer. https://github.com/AtlasOfLivingAustralia/fieldguide/issues/32

**Comment by adam-collins** [comment]
Closing this issue because it is currently working `https://fieldguide.ala.org.au/download/10112023-fieldguide1699578928693.pdf`
